### ISSUE TITLE
unable to get this working on El Capitan ( mac osX )

### ISSUE THREAD

**Issue by sc0ttruss** [AtomLinter/linter-foodcritic#8]
Installed from scratch, got linter-rubocop working.  Compared config with colleague on Yosimite, and the config looks all good.  Using "known bad" code for foodcritic, but foodcritic just does not run.  Rubucop runs every time, and even if I fix the rubucop things, foodcritic still does not run.   I installed chefdk, so running from the command line foodcritic works just fine on the file ( finds x4 issues).   

Also blew away the ~/.atom and started again.  Still no foodcritic.  Am pretty sure it is related to El Capitan.   Appreciate if anyone has seen same or has advice on what to try next.

file is below:-

```
file '/tmp/something' do
  punter 'root'
  action :create
end
```

**Comment by cawilliamson** [comment]
Did you ever resolve this issue?

**Comment by Arcanemagus** [comment]
Do you see any errors in the Developer Tools Console?
Does `foodcritic` work from a terminal?
Does it work when you launch Atom from within the terminal (with no other instances currently running)?

**Comment by cawilliamson** [comment]
I resolved this issue (on El Capitan too!)

You need to install language-chef, then restart Atom and select Chef instead of Ruby on the language dropdown (bottom right corner.) With this completed the plugin started working properly. I guess this was added to prevent it running on regular 'ol Ruby but the language-chef should likely be added as a dependency in this case.

Thanks

**Comment by Arcanemagus** [comment]
Ah, yes the scope needs to be `source.ruby.chef`. The README should be updated to reflect that.
